//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlStats.Wpf.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlStats.Wpf.Resources.Strings.AppResource - Copy", typeof(AppResource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string AreYouSureYouWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string AreYouSureYouWantToRemove {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided configuration might contain errors..
        /// </summary>
        public static string ConfigContainsError {
            get {
                return ResourceManager.GetString("ConfigContainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find user.
        /// </summary>
        public static string CouldntFindUser {
            get {
                return ResourceManager.GetString("CouldntFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the database. Check the database configuration..
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete team.
        /// </summary>
        public static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab access token.
        /// </summary>
        public static string GitLabAccessToken {
            get {
                return ResourceManager.GetString("GitLabAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab connection setup.
        /// </summary>
        public static string GitLabConnectionSetup {
            get {
                return ResourceManager.GetString("GitLabConnectionSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab server URL.
        /// </summary>
        public static string GitLabServerUrl {
            get {
                return ResourceManager.GetString("GitLabServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration.
        /// </summary>
        public static string InvalidConfig {
            get {
                return ResourceManager.GetString("InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage members.
        /// </summary>
        public static string ManageMembers {
            get {
                return ResourceManager.GetString("ManageMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database connection.
        /// </summary>
        public static string NoDatabaseConnection {
            get {
                return ResourceManager.GetString("NoDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be no internet connection or the host does not respond..
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user was found with the provided credentials..
        /// </summary>
        public static string NoUserFoundWithCredentials {
            get {
                return ResourceManager.GetString("NoUserFoundWithCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove member.
        /// </summary>
        public static string RemoveMember {
            get {
                return ResourceManager.GetString("RemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team was successfully created..
        /// </summary>
        public static string SuccessfullyCreatedTeam {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team added.
        /// </summary>
        public static string TeamAdded {
            get {
                return ResourceManager.GetString("TeamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team configuration.
        /// </summary>
        public static string TeamConfiguration {
            get {
                return ResourceManager.GetString("TeamConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
